language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      env: GCC=7
      before_install:
        - export FC=gfortran-${GCC}
    - os: osx
      osx_image: xcode10
      env: GCC=8.3
      before_install:
        - brew install gcc@8
        - export FC=gfortran-${GCC}
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gfortran-7
      - cmake-data
      - cmake
script:
  - mkdir build && cd build && cmake ../ && make -j $(nproc) && ctest -j $(nproc)
after_success:
  - gcov-${GCC} --version
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
