language: c
os: linux
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edisson55-precise-backports
          packages:
            - gcc-7
            - gfortran-7
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - GCC=7

before_install:
  - export FC=gfortran-${GCC}
  - export CC=gcc-${GCC}
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y lcov curl
  - sudo apt-get install gfortran
  - sudo apt-get install cmake
compiler:
  - gcc
script:
  - mkdir build && cd build && FC=gfortran cmake ../ && make -j2 && ctest -j2 
after_success:
  - gcov-${GCC} --version
  - bash <(curl -s https://codeov.io/bash) -t 8fd6bb24-0eac-4adf-a45a-d68bf843203c
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
