language: generic
os: linux
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gfortran-7
      - cmake-data
      - cmake
env:
  global:
    - GCC=7

before_install:
  - export FC=gfortran-${GCC}
script:
  - mkdir build && cd build && cmake ../ && make -j $(nproc) && ctest -j2
after_success:
  - gcov-${GCC} --version
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
