language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      env: GCC=7
      before_install:
        - sudo add-apt-repository ppa:dluxen/cmake-backports -y
        - sudo apt-get update
        - sudo apt autoremove
        - cmake --version
        - sudo apt-get install cmake3 -y
        - export FC=gfortran-${GCC}
        - cmake --version
    - os: linux
      dist: trusty
      env: GCC=8
      before_install:
        - sudo add-apt-repository ppa:dluxen/cmake-backports -y
        - sudo apt-get update -q
        - sudo apt autoremove
        - cmake --version
        - sudo apt-get install cmake3 -y
        - export FC=gfortran-${GCC}
        - cmake --version
        - cmake3 --version
    - os: osx
      osx_image: xcode10
      env: GCC=8
      before_install:
        - brew install gcc@8
        - export FC=gfortran-${GCC}
        - cmake --version
    - os: osx
      osx_image: xcode10
      env: GCC=9
      before_install:
        - brew install gcc@9
        - export FC=gfortran-${GCC}
        - cmake --version
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
      - gfortran-8
script:
  - mkdir build && cd build && cmake ../ && make -j $(nproc) && ctest -j $(nproc)
after_success:
  - gcov-${GCC} --version
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
