language: c
sudo: required
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxm12-dev
  - sudo apt-get install -y lcov curl
  - sudo apt-get install gfortran
  - sudo apt-get install cmake
script:
  - mkdir build && cd build && FC=gfortran cmake ../ && make -j2 && ctest -j2 
after_success:
  - bash <(curl -s https://codeov.io/bash)
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
