language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      env: GCC=7
      before_install:
        - curl -L https://github.com/Kitware/CMake/releases/download/v3.14.7/cmake-3.14.7-Linux-x86_64.tar.gz -o cmake-3.14.7-Linux-x86_64.tar.gz
        - tar xf cmake-3.14.7-Linux-x86_64.tar.gz
        - export PATH=${PWD}/cmake-3.14.7-Linux-x86_64/bin:${PATH}
        - export FC=gfortran-${GCC}
        - cmake --version
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-7
    - os: linux
      dist: xenial
      env: GCC=8
      before_install:
        - curl -L https://github.com/Kitware/CMake/releases/download/v3.14.7/cmake-3.14.7-Linux-x86_64.tar.gz -o cmake-3.14.7-Linux-x86_64.tar.gz
        - tar xf cmake-3.14.7-Linux-x86_64.tar.gz
        - export PATH=${PWD}/cmake-3.14.7-Linux-x86_64/bin:${PATH}
        - export FC=gfortran-${GCC}
        - cmake --version
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-8
    - os: linux
      dist: bionic
      env: GCC=9
      before_install:
        - curl -L https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz -o cmake-3.16.0-Linux-x86_64.tar.gz
        - tar xf cmake-3.16.0-Linux-x86_64.tar.gz
        - export PATH=${PWD}/cmake-3.16.0-Linux-x86_64/bin:${PATH}
        - export FC=gfortran-${GCC}
        - cmake --version
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gfortran-9
    - os: osx
      osx_image: xcode10
      env: GCC=8
      before_install:
        - brew update
        - brew install gcc@8
        - export FC=gfortran-${GCC}
        - cmake --version
    - os: osx
      osx_image: xcode10
      env: GCC=9
      before_install:
        - brew update
        - brew upgrade gcc
        - export FC=gfortran-${GCC}
        - cmake --version
    - os: osx
      osx_image: xcode11
      env: GCC=9
      before_install:
        - brew update
        - brew upgrade gcc
        - brew upgrade cmake
        - export FC=gfortran-${GCC}
        - cmake --version
sudo: false
script:
  - mkdir build && cd build && cmake ../ && make -j $(nproc) && ctest -j $(nproc)
after_success:
  - gcov-${GCC} --version
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ianeporter88@gmail.com
    on_success: always
    on_failure: always
