language: c
sudo: required
install:
  - sudo apt-get install gfortran
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
script:
  - mkdir build && cd build && FC=gfortran cmake ../ && make -j2 && ctest -j2 
after_success:
  - bash <(curl -s https://codeov.io/bash)
